name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p ${{ github.workspace }}/out

      - name: Build Docker Image
        run: docker build -t appimage-builder .

      - name: Run Container and Generate AppImage
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/out:/out \
            appimage-builder

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: out/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-release-windows:
    runs-on: windows-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          repository: "microsoft/vcpkg"
          path: "vcpkg"
          ref: "127402f1c75bb3d5ff6bce04b285faa4930a5aca"

      - name: Install vcpkg
        run: '& "$env:VCPKG_ROOT/bootstrap-vcpkg.bat"'

      - name: Create output directory
        run: mkdir -p ${{ github.workspace }}/out

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure cmake
        run: cmake --preset windows

      - name: Build
        run: cmake --build --preset windows-release

      - name: Collect build artifacts
        run: cp build-win/zoomer.exe ${{ github.workspace }}/out/zoomer-x64.exe

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: out/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
